# Generated by Django 3.1.2 on 2020-10-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='stakeholders',
        ),
        migrations.RemoveField(
            model_name='endeavor',
            name='team',
        ),
        migrations.RemoveField(
            model_name='endeavor',
            name='wayow',
        ),
        migrations.RemoveField(
            model_name='endeavor',
            name='work',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='endeavor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='softwareSystems',
        ),
        migrations.AddField(
            model_name='customer',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.project'),
        ),
        migrations.AddField(
            model_name='endeavor',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.project'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.customer'),
        ),
        migrations.AddField(
            model_name='requirements',
            name='solution',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.solution'),
        ),
        migrations.AddField(
            model_name='softwaresystems',
            name='solution',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.solution'),
        ),
        migrations.AddField(
            model_name='solution',
            name='project',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.project'),
        ),
        migrations.AddField(
            model_name='stakeholders',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.customer'),
        ),
        migrations.AddField(
            model_name='team',
            name='endeavor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.endeavor'),
        ),
        migrations.AddField(
            model_name='wayofwork',
            name='endeavor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.endeavor'),
        ),
        migrations.AddField(
            model_name='work',
            name='endeavor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.endeavor'),
        ),
    ]
