# Generated by Django 3.1.2 on 2020-10-01 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Endeavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareSystems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WayOfWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('requirements', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.requirements')),
                ('softwareSystems', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.softwaresystems')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(default='', max_length=70)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.customer')),
                ('endeavor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.endeavor')),
                ('solution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.solution')),
            ],
        ),
        migrations.AddField(
            model_name='endeavor',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.team'),
        ),
        migrations.AddField(
            model_name='endeavor',
            name='wayow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.wayofwork'),
        ),
        migrations.AddField(
            model_name='endeavor',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.work'),
        ),
        migrations.AddField(
            model_name='customer',
            name='opportunity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.opportunity'),
        ),
        migrations.AddField(
            model_name='customer',
            name='stakeholders',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.stakeholders'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('opportunity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.opportunity')),
                ('requirements', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.requirements')),
                ('softwaresys', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.softwaresystems')),
                ('stakeholders', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.stakeholders')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.team')),
                ('wayofwo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.wayofwork')),
                ('work', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.work')),
            ],
        ),
    ]
