# Generated by Django 2.2.5 on 2020-09-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0002_auto_20200930_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='opportunity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.Opportunity'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='stakeholders',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.Stakeholders'),
        ),
        migrations.AlterField(
            model_name='endeavor',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.Team'),
        ),
        migrations.AlterField(
            model_name='endeavor',
            name='wayow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.WayOfWork'),
        ),
        migrations.AlterField(
            model_name='endeavor',
            name='work',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.Work'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.Customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='endeavor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.Endeavor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.Solution'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='requirements',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.Requirements'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='softwareSystems',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essence.SoftwareSystems'),
        ),
    ]
