# Generated by Django 2.2.5 on 2020-10-01 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0003_auto_20200930_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='requirements',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='softwaresystems',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='stakeholders',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='team',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='wayofwork',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='work',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='opportunity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.Opportunity'),
        ),
        migrations.AddField(
            model_name='card',
            name='requirements',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.Requirements'),
        ),
        migrations.AddField(
            model_name='card',
            name='softwaresys',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.SoftwareSystems'),
        ),
        migrations.AddField(
            model_name='card',
            name='stakeholders',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.Stakeholders'),
        ),
        migrations.AddField(
            model_name='card',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.Team'),
        ),
        migrations.AddField(
            model_name='card',
            name='wayofwo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.WayOfWork'),
        ),
        migrations.AddField(
            model_name='card',
            name='work',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.Work'),
        ),
    ]
