# Generated by Django 3.1.2 on 2020-10-22 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0003_auto_20201004_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('task', models.CharField(default='', max_length=200)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essence.card')),
            ],
        ),
    ]
