# Generated by Django 3.1.2 on 2020-10-22 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essence', '0004_cardattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.opportunity'),
        ),
        migrations.AlterField(
            model_name='card',
            name='requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.requirements'),
        ),
        migrations.AlterField(
            model_name='card',
            name='softwaresys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.softwaresystems'),
        ),
        migrations.AlterField(
            model_name='card',
            name='stakeholders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.stakeholders'),
        ),
        migrations.AlterField(
            model_name='card',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.team'),
        ),
        migrations.AlterField(
            model_name='card',
            name='wayofwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.wayofwork'),
        ),
        migrations.AlterField(
            model_name='card',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='essence.work'),
        ),
    ]
